version: "3.8"
services:
  db:
    image: postgres:15
    command: postgres -c 'max_connections=450'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: people
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.6GB'

  api1: # API - Instância 01
    build: .
    depends_on:
      - db
    expose:
      - "3000"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: people
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  api2: # API - Instância 02
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: people
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: on-failure
    expose:
      - "3001"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - db
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'


## 1.5 CPU
## 3 GB